# Generated by Django 4.1.7 on 2023-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['type'], name='main_menu_type_65a26a_idx'),
        ),
    ]
