# Generated by Django 4.1.7 on 2023-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menu',
            new_name='main_menu_type_ix',
            old_name='main_menu_type_65a26a_idx',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
